### PR TITLE
Add `index.d.ts` file

### PR DESCRIPTION
**Pull request by xiaoxiangmoe**

### CODE REVIEW

**Comment by fisker** [comment]
I'm fine to add `index.d.ts`, but don't think worth to add types to source, and the deps.

**Comment by xiaoxiangmoe** [comment]
@fisker If we add types to source, and the deps. It would have better IDE support. But if you feel bad, we can remove the type in source. See the update.

**Comment by fisker** [comment]
Thank you! I'll merge when I have time to release.

**Review by fisker — APPROVED** [review]

**Comment by fisker** [comment]
Released as v3.1.0 https://github.com/prettier/parse-srcset/releases/tag/v3.1.0

**Pull request merged**
